/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables;


import com.example.demo.jooq.Keys;
import com.example.demo.jooq.Testdb;
import com.example.demo.jooq.tables.records.PrincipalRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Principal extends TableImpl<PrincipalRecord> {

    private static final long serialVersionUID = 329809515;

    /**
     * The reference instance of <code>testdb.principal</code>
     */
    public static final Principal PRINCIPAL = new Principal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PrincipalRecord> getRecordType() {
        return PrincipalRecord.class;
    }

    /**
     * The column <code>testdb.principal.id</code>.
     */
    public final TableField<PrincipalRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>testdb.principal.principal_type</code>.
     */
    public final TableField<PrincipalRecord, String> PRINCIPAL_TYPE = createField("principal_type", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>testdb.principal.teacher_id</code>.
     */
    public final TableField<PrincipalRecord, Long> TEACHER_ID = createField("teacher_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>testdb.principal</code> table reference
     */
    public Principal() {
        this("principal", null);
    }

    /**
     * Create an aliased <code>testdb.principal</code> table reference
     */
    public Principal(String alias) {
        this(alias, PRINCIPAL);
    }

    private Principal(String alias, Table<PrincipalRecord> aliased) {
        this(alias, aliased, null);
    }

    private Principal(String alias, Table<PrincipalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Testdb.TESTDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PrincipalRecord, Long> getIdentity() {
        return Keys.IDENTITY_PRINCIPAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PrincipalRecord> getPrimaryKey() {
        return Keys.KEY_PRINCIPAL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PrincipalRecord>> getKeys() {
        return Arrays.<UniqueKey<PrincipalRecord>>asList(Keys.KEY_PRINCIPAL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PrincipalRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PrincipalRecord, ?>>asList(Keys.FKJQ1GMCVQLA979I6L5CJTS2G1I);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Principal as(String alias) {
        return new Principal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Principal rename(String name) {
        return new Principal(name, null);
    }
}
