/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classz implements Serializable {

    private static final long serialVersionUID = 191886100;

    private Long    id;
    private Integer cnum;
    private Long    gradeId;

    public Classz() {}

    public Classz(Classz value) {
        this.id = value.id;
        this.cnum = value.cnum;
        this.gradeId = value.gradeId;
    }

    public Classz(
        Long    id,
        Integer cnum,
        Long    gradeId
    ) {
        this.id = id;
        this.cnum = cnum;
        this.gradeId = gradeId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCnum() {
        return this.cnum;
    }

    public void setCnum(Integer cnum) {
        this.cnum = cnum;
    }

    public Long getGradeId() {
        return this.gradeId;
    }

    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Classz (");

        sb.append(id);
        sb.append(", ").append(cnum);
        sb.append(", ").append(gradeId);

        sb.append(")");
        return sb.toString();
    }
}
