/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Grade implements Serializable {

    private static final long serialVersionUID = 1803454954;

    private Long    id;
    private Integer gnum;

    public Grade() {}

    public Grade(Grade value) {
        this.id = value.id;
        this.gnum = value.gnum;
    }

    public Grade(
        Long    id,
        Integer gnum
    ) {
        this.id = id;
        this.gnum = gnum;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getGnum() {
        return this.gnum;
    }

    public void setGnum(Integer gnum) {
        this.gnum = gnum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Grade (");

        sb.append(id);
        sb.append(", ").append(gnum);

        sb.append(")");
        return sb.toString();
    }
}
