/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PepoleBasic implements Serializable {

    private static final long serialVersionUID = -557642500;

    private Long      id;
    private Timestamp birthdayTime;
    private String    name;
    private String    sextType;

    public PepoleBasic() {}

    public PepoleBasic(PepoleBasic value) {
        this.id = value.id;
        this.birthdayTime = value.birthdayTime;
        this.name = value.name;
        this.sextType = value.sextType;
    }

    public PepoleBasic(
        Long      id,
        Timestamp birthdayTime,
        String    name,
        String    sextType
    ) {
        this.id = id;
        this.birthdayTime = birthdayTime;
        this.name = name;
        this.sextType = sextType;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Timestamp getBirthdayTime() {
        return this.birthdayTime;
    }

    public void setBirthdayTime(Timestamp birthdayTime) {
        this.birthdayTime = birthdayTime;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSextType() {
        return this.sextType;
    }

    public void setSextType(String sextType) {
        this.sextType = sextType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PepoleBasic (");

        sb.append(id);
        sb.append(", ").append(birthdayTime);
        sb.append(", ").append(name);
        sb.append(", ").append(sextType);

        sb.append(")");
        return sb.toString();
    }
}
