/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Principal implements Serializable {

    private static final long serialVersionUID = -609470218;

    private Long   id;
    private String principalType;
    private Long   teacherId;

    public Principal() {}

    public Principal(Principal value) {
        this.id = value.id;
        this.principalType = value.principalType;
        this.teacherId = value.teacherId;
    }

    public Principal(
        Long   id,
        String principalType,
        Long   teacherId
    ) {
        this.id = id;
        this.principalType = principalType;
        this.teacherId = teacherId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPrincipalType() {
        return this.principalType;
    }

    public void setPrincipalType(String principalType) {
        this.principalType = principalType;
    }

    public Long getTeacherId() {
        return this.teacherId;
    }

    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Principal (");

        sb.append(id);
        sb.append(", ").append(principalType);
        sb.append(", ").append(teacherId);

        sb.append(")");
        return sb.toString();
    }
}
