/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class School implements Serializable {

    private static final long serialVersionUID = -1061602272;

    private Long      id;
    private String    addr;
    private Timestamp foundTime;
    private String    name;

    public School() {}

    public School(School value) {
        this.id = value.id;
        this.addr = value.addr;
        this.foundTime = value.foundTime;
        this.name = value.name;
    }

    public School(
        Long      id,
        String    addr,
        Timestamp foundTime,
        String    name
    ) {
        this.id = id;
        this.addr = addr;
        this.foundTime = foundTime;
        this.name = name;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAddr() {
        return this.addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    public Timestamp getFoundTime() {
        return this.foundTime;
    }

    public void setFoundTime(Timestamp foundTime) {
        this.foundTime = foundTime;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("School (");

        sb.append(id);
        sb.append(", ").append(addr);
        sb.append(", ").append(foundTime);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
