/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = -2080635380;

    private Long id;
    private Long pepoleBasicId;
    private Long classzId;

    public Student() {}

    public Student(Student value) {
        this.id = value.id;
        this.pepoleBasicId = value.pepoleBasicId;
        this.classzId = value.classzId;
    }

    public Student(
        Long id,
        Long pepoleBasicId,
        Long classzId
    ) {
        this.id = id;
        this.pepoleBasicId = pepoleBasicId;
        this.classzId = classzId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPepoleBasicId() {
        return this.pepoleBasicId;
    }

    public void setPepoleBasicId(Long pepoleBasicId) {
        this.pepoleBasicId = pepoleBasicId;
    }

    public Long getClasszId() {
        return this.classzId;
    }

    public void setClasszId(Long classzId) {
        this.classzId = classzId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(id);
        sb.append(", ").append(pepoleBasicId);
        sb.append(", ").append(classzId);

        sb.append(")");
        return sb.toString();
    }
}
