/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherStudents implements Serializable {

    private static final long serialVersionUID = 1915761661;

    private Long teachersId;
    private Long studentsId;

    public TeacherStudents() {}

    public TeacherStudents(TeacherStudents value) {
        this.teachersId = value.teachersId;
        this.studentsId = value.studentsId;
    }

    public TeacherStudents(
        Long teachersId,
        Long studentsId
    ) {
        this.teachersId = teachersId;
        this.studentsId = studentsId;
    }

    public Long getTeachersId() {
        return this.teachersId;
    }

    public void setTeachersId(Long teachersId) {
        this.teachersId = teachersId;
    }

    public Long getStudentsId() {
        return this.studentsId;
    }

    public void setStudentsId(Long studentsId) {
        this.studentsId = studentsId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TeacherStudents (");

        sb.append(teachersId);
        sb.append(", ").append(studentsId);

        sb.append(")");
        return sb.toString();
    }
}
