/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teacher implements Serializable {

    private static final long serialVersionUID = -675582104;

    private Long id;
    private Long pepoleBasicId;
    private Long schoolId;

    public Teacher() {}

    public Teacher(Teacher value) {
        this.id = value.id;
        this.pepoleBasicId = value.pepoleBasicId;
        this.schoolId = value.schoolId;
    }

    public Teacher(
        Long id,
        Long pepoleBasicId,
        Long schoolId
    ) {
        this.id = id;
        this.pepoleBasicId = pepoleBasicId;
        this.schoolId = schoolId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPepoleBasicId() {
        return this.pepoleBasicId;
    }

    public void setPepoleBasicId(Long pepoleBasicId) {
        this.pepoleBasicId = pepoleBasicId;
    }

    public Long getSchoolId() {
        return this.schoolId;
    }

    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Teacher (");

        sb.append(id);
        sb.append(", ").append(pepoleBasicId);
        sb.append(", ").append(schoolId);

        sb.append(")");
        return sb.toString();
    }
}
