/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.records;


import com.example.demo.jooq.tables.Classz;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClasszRecord extends UpdatableRecordImpl<ClasszRecord> implements Record3<Long, Integer, Long> {

    private static final long serialVersionUID = 46938857;

    /**
     * Setter for <code>testdb.classz.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb.classz.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>testdb.classz.cnum</code>.
     */
    public void setCnum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb.classz.cnum</code>.
     */
    public Integer getCnum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>testdb.classz.grade_id</code>.
     */
    public void setGradeId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>testdb.classz.grade_id</code>.
     */
    public Long getGradeId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Integer, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Integer, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Classz.CLASSZ.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Classz.CLASSZ.CNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Classz.CLASSZ.GRADE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getGradeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasszRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasszRecord value2(Integer value) {
        setCnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasszRecord value3(Long value) {
        setGradeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClasszRecord values(Long value1, Integer value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClasszRecord
     */
    public ClasszRecord() {
        super(Classz.CLASSZ);
    }

    /**
     * Create a detached, initialised ClasszRecord
     */
    public ClasszRecord(Long id, Integer cnum, Long gradeId) {
        super(Classz.CLASSZ);

        set(0, id);
        set(1, cnum);
        set(2, gradeId);
    }
}
