/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.records;


import com.example.demo.jooq.tables.SchoolGrades;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchoolGradesRecord extends TableRecordImpl<SchoolGradesRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 2126747379;

    /**
     * Setter for <code>testdb.school_grades.school_id</code>.
     */
    public void setSchoolId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb.school_grades.school_id</code>.
     */
    public Long getSchoolId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>testdb.school_grades.grades_id</code>.
     */
    public void setGradesId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb.school_grades.grades_id</code>.
     */
    public Long getGradesId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SchoolGrades.SCHOOL_GRADES.SCHOOL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SchoolGrades.SCHOOL_GRADES.GRADES_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getSchoolId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getGradesId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolGradesRecord value1(Long value) {
        setSchoolId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolGradesRecord value2(Long value) {
        setGradesId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolGradesRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchoolGradesRecord
     */
    public SchoolGradesRecord() {
        super(SchoolGrades.SCHOOL_GRADES);
    }

    /**
     * Create a detached, initialised SchoolGradesRecord
     */
    public SchoolGradesRecord(Long schoolId, Long gradesId) {
        super(SchoolGrades.SCHOOL_GRADES);

        set(0, schoolId);
        set(1, gradesId);
    }
}
