/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.tables.records;


import com.example.demo.jooq.tables.Teacher;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherRecord extends UpdatableRecordImpl<TeacherRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1157787737;

    /**
     * Setter for <code>testdb.teacher.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>testdb.teacher.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>testdb.teacher.pepole_basic_id</code>.
     */
    public void setPepoleBasicId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>testdb.teacher.pepole_basic_id</code>.
     */
    public Long getPepoleBasicId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>testdb.teacher.school_id</code>.
     */
    public void setSchoolId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>testdb.teacher.school_id</code>.
     */
    public Long getSchoolId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Teacher.TEACHER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Teacher.TEACHER.PEPOLE_BASIC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Teacher.TEACHER.SCHOOL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPepoleBasicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getSchoolId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord value2(Long value) {
        setPepoleBasicId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord value3(Long value) {
        setSchoolId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeacherRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeacherRecord
     */
    public TeacherRecord() {
        super(Teacher.TEACHER);
    }

    /**
     * Create a detached, initialised TeacherRecord
     */
    public TeacherRecord(Long id, Long pepoleBasicId, Long schoolId) {
        super(Teacher.TEACHER);

        set(0, id);
        set(1, pepoleBasicId);
        set(2, schoolId);
    }
}
