/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq;


import com.example.demo.jooq.tables.Classz;
import com.example.demo.jooq.tables.Grade;
import com.example.demo.jooq.tables.PepoleBasic;
import com.example.demo.jooq.tables.Principal;
import com.example.demo.jooq.tables.School;
import com.example.demo.jooq.tables.SchoolGrades;
import com.example.demo.jooq.tables.Student;
import com.example.demo.jooq.tables.Teacher;
import com.example.demo.jooq.tables.TeacherClasszs;
import com.example.demo.jooq.tables.TeacherStudents;
import com.example.demo.jooq.tables.records.ClasszRecord;
import com.example.demo.jooq.tables.records.GradeRecord;
import com.example.demo.jooq.tables.records.PepoleBasicRecord;
import com.example.demo.jooq.tables.records.PrincipalRecord;
import com.example.demo.jooq.tables.records.SchoolGradesRecord;
import com.example.demo.jooq.tables.records.SchoolRecord;
import com.example.demo.jooq.tables.records.StudentRecord;
import com.example.demo.jooq.tables.records.TeacherClasszsRecord;
import com.example.demo.jooq.tables.records.TeacherRecord;
import com.example.demo.jooq.tables.records.TeacherStudentsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>testdb</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ClasszRecord, Long> IDENTITY_CLASSZ = Identities0.IDENTITY_CLASSZ;
    public static final Identity<GradeRecord, Long> IDENTITY_GRADE = Identities0.IDENTITY_GRADE;
    public static final Identity<PepoleBasicRecord, Long> IDENTITY_PEPOLE_BASIC = Identities0.IDENTITY_PEPOLE_BASIC;
    public static final Identity<PrincipalRecord, Long> IDENTITY_PRINCIPAL = Identities0.IDENTITY_PRINCIPAL;
    public static final Identity<SchoolRecord, Long> IDENTITY_SCHOOL = Identities0.IDENTITY_SCHOOL;
    public static final Identity<StudentRecord, Long> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;
    public static final Identity<TeacherRecord, Long> IDENTITY_TEACHER = Identities0.IDENTITY_TEACHER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClasszRecord> KEY_CLASSZ_PRIMARY = UniqueKeys0.KEY_CLASSZ_PRIMARY;
    public static final UniqueKey<GradeRecord> KEY_GRADE_PRIMARY = UniqueKeys0.KEY_GRADE_PRIMARY;
    public static final UniqueKey<PepoleBasicRecord> KEY_PEPOLE_BASIC_PRIMARY = UniqueKeys0.KEY_PEPOLE_BASIC_PRIMARY;
    public static final UniqueKey<PrincipalRecord> KEY_PRINCIPAL_PRIMARY = UniqueKeys0.KEY_PRINCIPAL_PRIMARY;
    public static final UniqueKey<SchoolRecord> KEY_SCHOOL_PRIMARY = UniqueKeys0.KEY_SCHOOL_PRIMARY;
    public static final UniqueKey<SchoolGradesRecord> KEY_SCHOOL_GRADES_UK_KQGTVGTTK4UCTTH050ARS78YD = UniqueKeys0.KEY_SCHOOL_GRADES_UK_KQGTVGTTK4UCTTH050ARS78YD;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_UK_KVSEQB7LNHJ12N0GE2CJII29C = UniqueKeys0.KEY_STUDENT_UK_KVSEQB7LNHJ12N0GE2CJII29C;
    public static final UniqueKey<TeacherRecord> KEY_TEACHER_PRIMARY = UniqueKeys0.KEY_TEACHER_PRIMARY;
    public static final UniqueKey<TeacherRecord> KEY_TEACHER_UK_35Q12M078DXPACGOMDD8R8RUK = UniqueKeys0.KEY_TEACHER_UK_35Q12M078DXPACGOMDD8R8RUK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ClasszRecord, GradeRecord> FKDGIFY2GAYJDKJYCB28EUA14U3 = ForeignKeys0.FKDGIFY2GAYJDKJYCB28EUA14U3;
    public static final ForeignKey<PrincipalRecord, TeacherRecord> FKJQ1GMCVQLA979I6L5CJTS2G1I = ForeignKeys0.FKJQ1GMCVQLA979I6L5CJTS2G1I;
    public static final ForeignKey<SchoolGradesRecord, SchoolRecord> FKFUQ5QT8CP37MC081C0TM1DSS0 = ForeignKeys0.FKFUQ5QT8CP37MC081C0TM1DSS0;
    public static final ForeignKey<SchoolGradesRecord, GradeRecord> FKTCSXC2TG73GPBP94RH9XICX41 = ForeignKeys0.FKTCSXC2TG73GPBP94RH9XICX41;
    public static final ForeignKey<StudentRecord, PepoleBasicRecord> FK7C7AJ3I9VKWMAP93F2OPE7SNW = ForeignKeys0.FK7C7AJ3I9VKWMAP93F2OPE7SNW;
    public static final ForeignKey<StudentRecord, ClasszRecord> FKOIXNMXEWP3TGVYCCTIG771GNV = ForeignKeys0.FKOIXNMXEWP3TGVYCCTIG771GNV;
    public static final ForeignKey<TeacherRecord, PepoleBasicRecord> FKEQS9I685Y0G9MXTHYBYJCI5W9 = ForeignKeys0.FKEQS9I685Y0G9MXTHYBYJCI5W9;
    public static final ForeignKey<TeacherRecord, SchoolRecord> FKRG46BNMGBCCCAYV14NAYMQG3R = ForeignKeys0.FKRG46BNMGBCCCAYV14NAYMQG3R;
    public static final ForeignKey<TeacherClasszsRecord, TeacherRecord> FKH2HF2ESDXMJPAUONRGQT7GYMI = ForeignKeys0.FKH2HF2ESDXMJPAUONRGQT7GYMI;
    public static final ForeignKey<TeacherClasszsRecord, ClasszRecord> FKIY6OB539N4EMV1OPOFLB20535 = ForeignKeys0.FKIY6OB539N4EMV1OPOFLB20535;
    public static final ForeignKey<TeacherStudentsRecord, TeacherRecord> FKKR9RJNME1KLPD0O8SNOCE0124 = ForeignKeys0.FKKR9RJNME1KLPD0O8SNOCE0124;
    public static final ForeignKey<TeacherStudentsRecord, StudentRecord> FKHSTOJ4YEP9M2VR6WH8CVQ1UPF = ForeignKeys0.FKHSTOJ4YEP9M2VR6WH8CVQ1UPF;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ClasszRecord, Long> IDENTITY_CLASSZ = createIdentity(Classz.CLASSZ, Classz.CLASSZ.ID);
        public static Identity<GradeRecord, Long> IDENTITY_GRADE = createIdentity(Grade.GRADE, Grade.GRADE.ID);
        public static Identity<PepoleBasicRecord, Long> IDENTITY_PEPOLE_BASIC = createIdentity(PepoleBasic.PEPOLE_BASIC, PepoleBasic.PEPOLE_BASIC.ID);
        public static Identity<PrincipalRecord, Long> IDENTITY_PRINCIPAL = createIdentity(Principal.PRINCIPAL, Principal.PRINCIPAL.ID);
        public static Identity<SchoolRecord, Long> IDENTITY_SCHOOL = createIdentity(School.SCHOOL, School.SCHOOL.ID);
        public static Identity<StudentRecord, Long> IDENTITY_STUDENT = createIdentity(Student.STUDENT, Student.STUDENT.ID);
        public static Identity<TeacherRecord, Long> IDENTITY_TEACHER = createIdentity(Teacher.TEACHER, Teacher.TEACHER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ClasszRecord> KEY_CLASSZ_PRIMARY = createUniqueKey(Classz.CLASSZ, "KEY_classz_PRIMARY", Classz.CLASSZ.ID);
        public static final UniqueKey<GradeRecord> KEY_GRADE_PRIMARY = createUniqueKey(Grade.GRADE, "KEY_grade_PRIMARY", Grade.GRADE.ID);
        public static final UniqueKey<PepoleBasicRecord> KEY_PEPOLE_BASIC_PRIMARY = createUniqueKey(PepoleBasic.PEPOLE_BASIC, "KEY_pepole_basic_PRIMARY", PepoleBasic.PEPOLE_BASIC.ID);
        public static final UniqueKey<PrincipalRecord> KEY_PRINCIPAL_PRIMARY = createUniqueKey(Principal.PRINCIPAL, "KEY_principal_PRIMARY", Principal.PRINCIPAL.ID);
        public static final UniqueKey<SchoolRecord> KEY_SCHOOL_PRIMARY = createUniqueKey(School.SCHOOL, "KEY_school_PRIMARY", School.SCHOOL.ID);
        public static final UniqueKey<SchoolGradesRecord> KEY_SCHOOL_GRADES_UK_KQGTVGTTK4UCTTH050ARS78YD = createUniqueKey(SchoolGrades.SCHOOL_GRADES, "KEY_school_grades_UK_kqgtvgttk4uctth050ars78yd", SchoolGrades.SCHOOL_GRADES.GRADES_ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = createUniqueKey(Student.STUDENT, "KEY_student_PRIMARY", Student.STUDENT.ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_UK_KVSEQB7LNHJ12N0GE2CJII29C = createUniqueKey(Student.STUDENT, "KEY_student_UK_kvseqb7lnhj12n0ge2cjii29c", Student.STUDENT.PEPOLE_BASIC_ID);
        public static final UniqueKey<TeacherRecord> KEY_TEACHER_PRIMARY = createUniqueKey(Teacher.TEACHER, "KEY_teacher_PRIMARY", Teacher.TEACHER.ID);
        public static final UniqueKey<TeacherRecord> KEY_TEACHER_UK_35Q12M078DXPACGOMDD8R8RUK = createUniqueKey(Teacher.TEACHER, "KEY_teacher_UK_35q12m078dxpacgomdd8r8ruk", Teacher.TEACHER.PEPOLE_BASIC_ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ClasszRecord, GradeRecord> FKDGIFY2GAYJDKJYCB28EUA14U3 = createForeignKey(com.example.demo.jooq.Keys.KEY_GRADE_PRIMARY, Classz.CLASSZ, "FKdgify2gayjdkjycb28eua14u3", Classz.CLASSZ.GRADE_ID);
        public static final ForeignKey<PrincipalRecord, TeacherRecord> FKJQ1GMCVQLA979I6L5CJTS2G1I = createForeignKey(com.example.demo.jooq.Keys.KEY_TEACHER_PRIMARY, Principal.PRINCIPAL, "FKjq1gmcvqla979i6l5cjts2g1i", Principal.PRINCIPAL.TEACHER_ID);
        public static final ForeignKey<SchoolGradesRecord, SchoolRecord> FKFUQ5QT8CP37MC081C0TM1DSS0 = createForeignKey(com.example.demo.jooq.Keys.KEY_SCHOOL_PRIMARY, SchoolGrades.SCHOOL_GRADES, "FKfuq5qt8cp37mc081c0tm1dss0", SchoolGrades.SCHOOL_GRADES.SCHOOL_ID);
        public static final ForeignKey<SchoolGradesRecord, GradeRecord> FKTCSXC2TG73GPBP94RH9XICX41 = createForeignKey(com.example.demo.jooq.Keys.KEY_GRADE_PRIMARY, SchoolGrades.SCHOOL_GRADES, "FKtcsxc2tg73gpbp94rh9xicx41", SchoolGrades.SCHOOL_GRADES.GRADES_ID);
        public static final ForeignKey<StudentRecord, PepoleBasicRecord> FK7C7AJ3I9VKWMAP93F2OPE7SNW = createForeignKey(com.example.demo.jooq.Keys.KEY_PEPOLE_BASIC_PRIMARY, Student.STUDENT, "FK7c7aj3i9vkwmap93f2ope7snw", Student.STUDENT.PEPOLE_BASIC_ID);
        public static final ForeignKey<StudentRecord, ClasszRecord> FKOIXNMXEWP3TGVYCCTIG771GNV = createForeignKey(com.example.demo.jooq.Keys.KEY_CLASSZ_PRIMARY, Student.STUDENT, "FKoixnmxewp3tgvycctig771gnv", Student.STUDENT.CLASSZ_ID);
        public static final ForeignKey<TeacherRecord, PepoleBasicRecord> FKEQS9I685Y0G9MXTHYBYJCI5W9 = createForeignKey(com.example.demo.jooq.Keys.KEY_PEPOLE_BASIC_PRIMARY, Teacher.TEACHER, "FKeqs9i685y0g9mxthybyjci5w9", Teacher.TEACHER.PEPOLE_BASIC_ID);
        public static final ForeignKey<TeacherRecord, SchoolRecord> FKRG46BNMGBCCCAYV14NAYMQG3R = createForeignKey(com.example.demo.jooq.Keys.KEY_SCHOOL_PRIMARY, Teacher.TEACHER, "FKrg46bnmgbcccayv14naymqg3r", Teacher.TEACHER.SCHOOL_ID);
        public static final ForeignKey<TeacherClasszsRecord, TeacherRecord> FKH2HF2ESDXMJPAUONRGQT7GYMI = createForeignKey(com.example.demo.jooq.Keys.KEY_TEACHER_PRIMARY, TeacherClasszs.TEACHER_CLASSZS, "FKh2hf2esdxmjpauonrgqt7gymi", TeacherClasszs.TEACHER_CLASSZS.TEACHERS_ID);
        public static final ForeignKey<TeacherClasszsRecord, ClasszRecord> FKIY6OB539N4EMV1OPOFLB20535 = createForeignKey(com.example.demo.jooq.Keys.KEY_CLASSZ_PRIMARY, TeacherClasszs.TEACHER_CLASSZS, "FKiy6ob539n4emv1opoflb20535", TeacherClasszs.TEACHER_CLASSZS.CLASSZS_ID);
        public static final ForeignKey<TeacherStudentsRecord, TeacherRecord> FKKR9RJNME1KLPD0O8SNOCE0124 = createForeignKey(com.example.demo.jooq.Keys.KEY_TEACHER_PRIMARY, TeacherStudents.TEACHER_STUDENTS, "FKkr9rjnme1klpd0o8snoce0124", TeacherStudents.TEACHER_STUDENTS.TEACHERS_ID);
        public static final ForeignKey<TeacherStudentsRecord, StudentRecord> FKHSTOJ4YEP9M2VR6WH8CVQ1UPF = createForeignKey(com.example.demo.jooq.Keys.KEY_STUDENT_PRIMARY, TeacherStudents.TEACHER_STUDENTS, "FKhstoj4yep9m2vr6wh8cvq1upf", TeacherStudents.TEACHER_STUDENTS.STUDENTS_ID);
    }
}
