/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq;


import com.example.demo.jooq.tables.Classz;
import com.example.demo.jooq.tables.Grade;
import com.example.demo.jooq.tables.PepoleBasic;
import com.example.demo.jooq.tables.Principal;
import com.example.demo.jooq.tables.School;
import com.example.demo.jooq.tables.SchoolGrades;
import com.example.demo.jooq.tables.Student;
import com.example.demo.jooq.tables.Teacher;
import com.example.demo.jooq.tables.TeacherClasszs;
import com.example.demo.jooq.tables.TeacherStudents;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Testdb extends SchemaImpl {

    private static final long serialVersionUID = 518153720;

    /**
     * The reference instance of <code>testdb</code>
     */
    public static final Testdb TESTDB = new Testdb();

    /**
     * The table <code>testdb.classz</code>.
     */
    public final Classz CLASSZ = com.example.demo.jooq.tables.Classz.CLASSZ;

    /**
     * The table <code>testdb.grade</code>.
     */
    public final Grade GRADE = com.example.demo.jooq.tables.Grade.GRADE;

    /**
     * The table <code>testdb.pepole_basic</code>.
     */
    public final PepoleBasic PEPOLE_BASIC = com.example.demo.jooq.tables.PepoleBasic.PEPOLE_BASIC;

    /**
     * The table <code>testdb.principal</code>.
     */
    public final Principal PRINCIPAL = com.example.demo.jooq.tables.Principal.PRINCIPAL;

    /**
     * The table <code>testdb.school</code>.
     */
    public final School SCHOOL = com.example.demo.jooq.tables.School.SCHOOL;

    /**
     * The table <code>testdb.school_grades</code>.
     */
    public final SchoolGrades SCHOOL_GRADES = com.example.demo.jooq.tables.SchoolGrades.SCHOOL_GRADES;

    /**
     * The table <code>testdb.student</code>.
     */
    public final Student STUDENT = com.example.demo.jooq.tables.Student.STUDENT;

    /**
     * The table <code>testdb.teacher</code>.
     */
    public final Teacher TEACHER = com.example.demo.jooq.tables.Teacher.TEACHER;

    /**
     * The table <code>testdb.teacher_classzs</code>.
     */
    public final TeacherClasszs TEACHER_CLASSZS = com.example.demo.jooq.tables.TeacherClasszs.TEACHER_CLASSZS;

    /**
     * The table <code>testdb.teacher_students</code>.
     */
    public final TeacherStudents TEACHER_STUDENTS = com.example.demo.jooq.tables.TeacherStudents.TEACHER_STUDENTS;

    /**
     * No further instances allowed
     */
    private Testdb() {
        super("testdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Classz.CLASSZ,
            Grade.GRADE,
            PepoleBasic.PEPOLE_BASIC,
            Principal.PRINCIPAL,
            School.SCHOOL,
            SchoolGrades.SCHOOL_GRADES,
            Student.STUDENT,
            Teacher.TEACHER,
            TeacherClasszs.TEACHER_CLASSZS,
            TeacherStudents.TEACHER_STUDENTS);
    }
}
